### ISSUE TITLE
"resource" folder name

### ISSUE THREAD

**Issue by mnicolas80** [padosoft/laravel-composer-security#1]
Hi!

I've just installed the package and after I run the publish command, it created a "resource" folder in app root. At the same level, Laravel uses another folder named "resources". Isn't it better to generate the packages "resource" contents in Laravel's default "resources" folder?
for example:

```
        $this->publishes([
            __DIR__ . '/views' => base_path('resource/views/vendor/composer-security-check'),
        ]);
```

becomes:

```
        $this->publishes([
            __DIR__ . '/views' => base_path('resources/views/vendor/composer-security-check'),
        ]);
```

Btw, great package!

Thank you

**Comment by lopadova** [comment]
Hi peter,
you're right, the choice of the name of the folder was an oversight.
I correct the package as soon as possible.
thanks for the tip!
